include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    depend_on_referenced_packages: ignore
    prefer_const_constructors: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
